export const categories = [
  { name: "Birthday", slug: "birthday", icon: "🎂" },
  { name: "Anniversary", slug: "anniversary", icon: "💝" },
  { name: "Couple", slug: "couple", icon: "👩‍❤️‍👨" },
  { name: "Corporate", slug: "corporate", icon: "💼" },
  { name: "Combo", slug: "combo", icon: "🎁" },
  { name: "Mugs", slug: "mugs", icon: "☕" },
  { name: "Frames", slug: "frames", icon: "🖼️" },
  { name: "Keychains", slug: "keychains", icon: "🔑" },
  { name: "Customized T Shirt", slug: "customized-t-shirt", icon: "👕" },
  { name: "Acrylic Frames", slug: "acrylic-frames", icon: "✨" },
  { name: "Stickers and Labels", slug: "stickers-and-labels", icon: "🏷️" },
  { name: "Resin Art", slug: "resin-art", icon: "🌊" },
];
export type Product = {
  slug: string;
  name: string;
  category: string;
  price: string;
  oldPrice?: string;
  offer?: string;
  image: string;
  description: string;
  requiredPhotos?: string;
  requiredDetails?: string;
  photoSize?: string;
};

export const products: Product[] = [
  /* ---------------- FEATURED PRODUCTS ---------------- */
  {
    slug: "customized-photo-collage",
    name: "Customized Photo Collage Frame",
    category: "featured",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/best1.jpg",
    description: "Turn your favorite memories into a stunning personalized photo collage frame. Carefully designed with your cherished moments, this frame is perfect for birthdays, anniversaries, weddings, and special occasions. Crafted with premium-quality materials to make every memory last forever.",
    requiredPhotos: "15–30 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "google-collage-frame",
    name: "Google Collage Frame",
    category: "featured",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/best2.jpg",
    description: "Make your memories unforgettable with our unique Google Search-style photo collage frame. Personalize it with your favorite pictures and custom text to create a fun and creative gift for your loved ones.",
    requiredPhotos: "8–15 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "spotify-photo-frame",
    name: "Spotify Photo Frame",
    category: "featured",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/best3.jpg",
    description: "Celebrate your favorite song and special memories in one beautiful frame. Personalize it with your photo, song title, artist name, and optional Spotify QR code for a meaningful keepsake.",
    requiredPhotos: "1 High-Quality Photo",
    requiredDetails: "Song Name, Artist Name and Spotify Link/QR Code (Optional)",
    photoSize: "",
  },
  {
    slug: "moon-shape-photo-frame",
    name: "Moon Shape Photo Frame",
    category: "featured",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/best4.jpg",
    description: "Capture your special moments with a personalized moon-shaped photo frame featuring your favorite photos, memorable date, and heartfelt message. A perfect gift for birthdays, anniversaries, and loved ones.",
    requiredPhotos: "12–20 High-Quality Photos",
    requiredDetails: "Special Date and Custom Message",
    photoSize: "",
  },
  {
    slug: "photo-clip-string-light",
    name: "Photo Clip String Light",
    category: "featured",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/new1.jpg",
    description: "Light up your memories with our decorative LED photo clip string lights. Display your favorite pictures beautifully and add a warm, cozy touch to any room.",
    requiredPhotos: "10–30 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "customized-photo-prints",
    name: "Customized Portrait",
    category: "featured",
    price: "₹249",
    oldPrice: "₹498",
    offer: "50% OFF",
    image: "/images/new2.jpg",
    description: "Print your favorite memories on premium-quality photo paper with vibrant colors and a long-lasting finish. Package includes 25 pieces. Perfect for albums, scrapbooks, room decoration, and gifting.",
    requiredPhotos: "10–100 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "custom-photo-collage",
    name: "Custom Photo Collage",
    category: "featured",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/new3.jpg",
    description: "Create a beautiful personalized collage frame with your favorite memories. A perfect gift for birthdays, anniversaries, and special occasions.",
    requiredPhotos: "15–30 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "students-teacher-photo-frame",
    name: "Students & Teacher Photo Frame",
    category: "featured",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/new4.jpg",
    description: "Celebrate the special bond between students and teachers with a customized photo frame. It is perfect for farewell events, graduation celebrations, Teacher's Day, and meaningful appreciation gifts.",
    requiredPhotos: "20–50 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },

  /* ---------------- BIRTHDAY ---------------- */
  {
    slug: "birthday-customized-photo-frame",
    name: "Customized Photo Frame",
    category: "birthday",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/birthday/birthday-sample-1.jpg",
    description: "Make birthdays extra special with a personalized photo frame customized with your favorite memory.",
    requiredPhotos: "1 High-Quality Photo",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "birthday-collage-photo-frame",
    name: "Collage Photo Frame",
    category: "birthday",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/birthday/birthday-sample-2.jpg",
    description: "A birthday collage frame to showcase multiple favorite moments together in one frame.",
    requiredPhotos: "5–10 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "birthday-photo-clock",
    name: "Photo Clock",
    category: "birthday",
    price: "₹350",
    oldPrice: "₹700",
    offer: "50% OFF",
    image: "/images/birthday/birthday-sample-4.jpg",
    description: "Custom wall clock featuring birthday photo prints for a memorable utility gift.",
    requiredPhotos: "1–4 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "birthday-photo-calendar",
    name: "Photo Calendar",
    category: "birthday",
    price: "₹250",
    oldPrice: "₹500",
    offer: "50% OFF",
    image: "/images/birthday/birthday-sample-5.jpg",
    description: "Personalized birthday photo calendar to cherish memories month by month.",
    requiredPhotos: "12 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "birthday-customized-mugs",
    name: "Birthday Customized Mugs",
    category: "birthday",
    price: "₹179",
    oldPrice: "₹358",
    offer: "50% OFF",
    image: "/images/birthday/birthday-sample-6.jpg",
    description: "Custom printed coffee mug with birthday wishes and personal pictures.",
    requiredPhotos: "1–2 High-Quality Photos",
    requiredDetails: "Name or custom text message",
    photoSize: "",
  },
  {
    slug: "birthday-custom-keychains",
    name: "Birthday Custom Keychains",
    category: "birthday",
    price: "₹79",
    oldPrice: "₹158",
    offer: "50% OFF",
    image: "/images/birthday/birthday-sample-7.jpg",
    description: "Personalized acrylic/wooden keychain with birthday picture or name print.",
    requiredPhotos: "1 High-Quality Photo",
    requiredDetails: "Name or text",
    photoSize: "",
  },
  {
    slug: "birthday-magazines",
    name: "Birthday Magazines",
    category: "birthday",
    price: "₹499",
    oldPrice: "₹998",
    offer: "50% OFF",
    image: "/images/birthday/birthday-sample-8.jpg",
    description: "Custom magazine cover style photo print celebrating a birthday star.",
    requiredPhotos: "5–10 High-Quality Photos",
    requiredDetails: "Custom headlines and names",
    photoSize: "Available Sizes: 4×6 (A6 Size), 6×8 (A5 Size)",
  },
  {
    slug: "birthday-custom-photo-book",
    name: "Custom Photo Book",
    category: "birthday",
    price: "₹499",
    oldPrice: "₹998",
    offer: "50% OFF",
    image: "/images/birthday/birthday-sample-9.jpg",
    description: "Hardcover photo album capturing all special birthday celebrations.",
    requiredPhotos: "20–40 High-Quality Photos",
    requiredDetails: "",
    photoSize: "Available Sizes: 4×6 (A6 Size), 6×8 (A5 Size)",
  },

  /* ---------------- ANNIVERSARY ---------------- */
  {
    slug: "anniversary-photo-frame",
    name: "Anniversary Photo Frame",
    category: "anniversary",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/anniversary/anniversary-1.jpg",
    description: "Celebrate years of togetherness with a customized anniversary photo frame.",
    requiredPhotos: "1 High-Quality Photo",
    requiredDetails: "Names & Anniversary Date",
    photoSize: "",
  },
  {
    slug: "anniversary-collage-photo-frame",
    name: "Collage Photo Frame",
    category: "anniversary",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/anniversary/anniversary-2.jpg",
    description: "Combine journey photos into a beautiful anniversary collage frame.",
    requiredPhotos: "10–20 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "anniversary-mosaic-photo-frame",
    name: "Mosaic Photo Frame",
    category: "anniversary",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/anniversary/anniversary-3.jpg",
    description: "Unique photo mosaic made up of dozens of small memories forming one main image.",
    requiredPhotos: "30–50 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "anniversary-photo-wall-collage",
    name: "Photo Wall Collage",
    category: "anniversary",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/anniversary/anniversary-5.jpg",
    description: "Multi-frame wall set designed to decorate your home with anniversary memories.",
    requiredPhotos: "15–30 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "anniversary-mugs",
    name: "Anniversary Mugs",
    category: "anniversary",
    price: "₹179",
    oldPrice: "₹358",
    offer: "50% OFF",
    image: "/images/anniversary/anniversary-6.jpg",
    description: "Matching or single customized coffee mugs for anniversary celebrations.",
    requiredPhotos: "1–2 High-Quality Photos",
    requiredDetails: "Anniversary Date & Names",
    photoSize: "",
  },
  {
    slug: "anniversary-keychains",
    name: "Anniversary Keychains",
    category: "anniversary",
    price: "₹79",
    oldPrice: "₹158",
    offer: "50% OFF",
    image: "/images/anniversary/anniversary-7.jpg",
    description: "Cute customized keychains for couples celebrating their anniversary.",
    requiredPhotos: "1–2 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "anniversary-custom-photo-book",
    name: "Custom Photo Book",
    category: "anniversary",
    price: "₹499",
    oldPrice: "₹998",
    offer: "50% OFF",
    image: "/images/anniversary/anniversary-8.jpg",
    description: "A memory album chronicling your shared years and special milestones.",
    requiredPhotos: "20–50 High-Quality Photos",
    requiredDetails: "",
    photoSize: "Available Sizes: 4×6 (A6 Size), 6×8 (A5 Size)",
  },
  {
    slug: "love-message-frame",
    name: "Love Message Frame",
    category: "anniversary",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/anniversary/anniversary-9.jpg",
    description: "Customized photo frame with heartfelt anniversary love notes and quotes.",
    requiredPhotos: "1–3 High-Quality Photos",
    requiredDetails: "Custom Message Text",
    photoSize: "",
  },

  /* ---------------- COUPLE ---------------- */
  {
    slug: "couple-photo-frame",
    name: "Couple Photo Frame",
    category: "couple",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/couple/couple-1.jpg",
    description: "Romantic customized photo frame crafted specifically for couples.",
    requiredPhotos: "1–2 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "customized-couple-mugs",
    name: "Customized Couple Mugs",
    category: "couple",
    price: "₹179",
    oldPrice: "₹358",
    offer: "50% OFF",
    image: "/images/couple/couple-2.jpg",
    description: "Pair of personalized ceramic mugs for couples.",
    requiredPhotos: "2 High-Quality Photos",
    requiredDetails: "Couple Names",
    photoSize: "",
  },
  {
    slug: "couple-customized-keychains",
    name: "Customized Keychains",
    category: "couple",
    price: "₹79",
    oldPrice: "₹158",
    offer: "50% OFF",
    image: "/images/couple/couple-3.jpg",
    description: "Matching or single couple keychain printed with special dates or photos.",
    requiredPhotos: "1–2 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "love-message-photo-frame",
    name: "Love Message Photo Frame",
    category: "couple",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/couple/couple-4.jpg",
    description: "A romantic frame that combines your favorite couple photo with a personal love quote.",
    requiredPhotos: "1 High-Quality Photo",
    requiredDetails: "Personalized Message",
    photoSize: "",
  },
  {
    slug: "couple-collage-photo-frame",
    name: "Collage Photo Frame",
    category: "couple",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/couple/couple-6.jpg",
    description: "Display multiple couple memories in a beautifully structured collage.",
    requiredPhotos: "8–15 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "couple-mosaic-photo-frame",
    name: "Mosaic Photo Frame",
    category: "couple",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/couple/couple-7.jpg",
    description: "A artistic mosaic frame constructed from tiny romantic photos.",
    requiredPhotos: "25–40 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "customized-photo-album",
    name: "Customized Photo Album",
    category: "couple",
    price: "₹499",
    oldPrice: "₹998",
    offer: "50% OFF",
    image: "/images/couple/couple-8.jpg",
    description: "High-quality bound photo album to preserve romantic memories.",
    requiredPhotos: "20–50 High-Quality Photos",
    requiredDetails: "",
    photoSize: "Available Sizes: 4×6 (A6 Size), 6×8 (A5 Size)",
  },
  {
    slug: "couple-customized-photo-book",
    name: "Customized Photo Book",
    category: "couple",
    price: "₹499",
    oldPrice: "₹998",
    offer: "50% OFF",
    image: "/images/couple/couple-9.jpg",
    description: "Premium coffee table style photo book for couples.",
    requiredPhotos: "30–60 High-Quality Photos",
    requiredDetails: "",
    photoSize: "Available Sizes: 4×6 (A6 Size), 6×8 (A5 Size)",
  },
  {
    slug: "customized-magazines",
    name: "Customized Magazines",
    category: "couple",
    price: "₹499",
    oldPrice: "₹998",
    offer: "50% OFF",
    image: "/images/couple/couple-10.jpg",
    description: "Fun couple-themed magazine print tailored with personal stories and photos.",
    requiredPhotos: "5–10 High-Quality Photos",
    requiredDetails: "Names & Custom Headlines",
    photoSize: "Available Sizes: 4×6 (A6 Size), 6×8 (A5 Size)",
  },

  /* ---------------- CORPORATE ---------------- */
  {
    slug: "corporate-customized-mug",
    name: "Customized Mug",
    category: "corporate",
    price: "₹179",
    oldPrice: "₹358",
    offer: "50% OFF",
    image: "/images/corporate/corporate-1.jpg",
    description: "Branded corporate mugs with company logos and employee names.",
    requiredPhotos: "1 High-Quality Logo/Photo",
    requiredDetails: "Company Name or Employee Name",
    photoSize: "",
  },
  {
    slug: "corporate-customized-keychains",
    name: "Customized Keychains",
    category: "corporate",
    price: "₹79",
    oldPrice: "₹158",
    offer: "50% OFF",
    image: "/images/corporate/corporate-2.jpg",
    description: "Bulk or individual corporate keychains for events and employee gifting.",
    requiredPhotos: "1 High-Quality Logo",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "customized-water-bottle",
    name: "Customized Water Bottle",
    category: "corporate",
    price: "₹499",
    oldPrice: "₹998",
    offer: "50% OFF",
    image: "/images/corporate/corporate-3.jpg",
    description: "Stainless steel corporate water bottle printed with company branding.",
    requiredPhotos: "1 Logo File",
    requiredDetails: "Name / Employee ID",
    photoSize: "",
  },
  {
    slug: "corporate-photo-frame",
    name: "Photo Frame",
    category: "corporate",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/corporate/corporate-4.jpg",
    description: "Professional desk or wall photo frame for corporate achievements.",
    requiredPhotos: "1 High-Quality Photo/Logo",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "logo-printed-keychains",
    name: "Logo Printed Keychains",
    category: "corporate",
    price: "₹79",
    oldPrice: "₹158",
    offer: "50% OFF",
    image: "/images/corporate/corporate-5.jpg",
    description: "Durable metallic or acrylic keychains featuring crisp company logo prints.",
    requiredPhotos: "Vector or High-Res Logo",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "customized-calendar",
    name: "Customized Calendar",
    category: "corporate",
    price: "₹399",
    oldPrice: "₹798",
    offer: "50% OFF",
    image: "/images/corporate/corporate-6.jpg",
    description: "Desk or wall corporate calendar printed with company branding.",
    requiredPhotos: "12 High-Quality Images/Logos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "motivational-photo-frame",
    name: "Motivational Photo Frame",
    category: "corporate",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/corporate/corporate-8.jpg",
    description: "Inspirational quote prints designed for office walls and workstations.",
    requiredPhotos: "Optional Photo",
    requiredDetails: "Custom Quote (Optional)",
    photoSize: "",
  },
  {
    slug: "wall-frames",
    name: "Wall Frames",
    category: "corporate",
    price: "₹699",
    oldPrice: "₹1398",
    offer: "50% OFF",
    image: "/images/corporate/corporate-9.jpg",
    description: "Large format office decor frames for team photos or company values.",
    requiredPhotos: "1–5 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },

  /* ---------------- COMBO ---------------- */
  {
    slug: "photo-frame-mug-combo",
    name: "Photo Frame + Mug",
    category: "combo",
    price: "₹429",
    oldPrice: "₹858",
    offer: "50% OFF",
    image: "/images/combo/combo-1.jpg",
    description: "Perfect gifting set containing a personalized frame and matching ceramic mug.",
    requiredPhotos: "2–3 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "mug-keychains-combo",
    name: "Mug + Keychains",
    category: "combo",
    price: "₹249",
    oldPrice: "₹498",
    offer: "50% OFF",
    image: "/images/combo/combo-2.jpg",
    description: "Combo set featuring a custom coffee mug and matching keychain.",
    requiredPhotos: "1–2 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "photo-frame-keychains-combo",
    name: "Photo Frame + Keychains",
    category: "combo",
    price: "₹429",
    oldPrice: "₹858",
    offer: "50% OFF",
    image: "/images/combo/combo-3.jpg",
    description: "Custom frame combined with a personal photo keychain.",
    requiredPhotos: "2–4 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "mug-greeting-card-combo",
    name: "Mug + Greeting Card",
    category: "combo",
    price: "₹249",
    oldPrice: "₹498",
    offer: "50% OFF",
    image: "/images/combo/combo-4.jpg",
    description: "A custom printed photo mug paired with a personalized greeting card.",
    requiredPhotos: "1–2 High-Quality Photos",
    requiredDetails: "Greeting Card Message",
    photoSize: "",
  },

  /* ---------------- MUGS ---------------- */
  {
    slug: "photo-mug",
    name: "Photo Mug",
    category: "mugs",
    price: "₹179",
    oldPrice: "₹358",
    offer: "50% OFF",
    image: "/images/mugs/mugs-1.jpg",
    description: "Classic ceramic coffee mug custom-printed with your favorite photo.",
    requiredPhotos: "1–2 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "couple-mug-item",
    name: "Couple Mug",
    category: "mugs",
    price: "₹179",
    oldPrice: "₹358",
    offer: "50% OFF",
    image: "/images/mugs/mugs-2.jpg",
    description: "Romantic mug design crafted specifically for couples.",
    requiredPhotos: "1–2 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "magic-mug",
    name: "Magic Mug",
    category: "mugs",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/mugs/mugs-3.jpg",
    description: "Color-changing magic mug that reveals your hidden picture when hot liquid is poured.",
    requiredPhotos: "1 High-Quality Photo",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "name-printed-mugs",
    name: "Name Printed Mugs",
    category: "mugs",
    price: "₹179",
    oldPrice: "₹358",
    offer: "50% OFF",
    image: "/images/mugs/mugs-4.jpg",
    description: "Stylish typography mug customized with your name or monogram.",
    requiredPhotos: "Optional Photo",
    requiredDetails: "Name / Custom Text",
    photoSize: "",
  },
  {
    slug: "birthday-mug",
    name: "Birthday Mug",
    category: "mugs",
    price: "₹179",
    oldPrice: "₹358",
    offer: "50% OFF",
    image: "/images/mugs/mugs-5.jpg",
    description: "Fun birthday themed coffee mug.",
    requiredPhotos: "1 High-Quality Photo",
    requiredDetails: "Name / Birth Date",
    photoSize: "",
  },
  {
    slug: "best-friends-mug",
    name: "Best Friends Mug",
    category: "mugs",
    price: "₹179",
    oldPrice: "₹358",
    offer: "50% OFF",
    image: "/images/mugs/mugs-6.jpg",
    description: "Celebrate friendship with a dedicated custom best friends photo mug.",
    requiredPhotos: "1–2 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "anniversary-mug",
    name: "Anniversary Mug",
    category: "mugs",
    price: "₹179",
    oldPrice: "₹358",
    offer: "50% OFF",
    image: "/images/mugs/mugs-7.jpg",
    description: "Custom anniversary print coffee mug.",
    requiredPhotos: "1–2 High-Quality Photos",
    requiredDetails: "Anniversary Date",
    photoSize: "",
  },
  {
    slug: "magic-mirror",
    name: "Magic Mirror",
    category: "mugs",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/mugs/mugs-8.jpg",
    description: "LED Magic mirror frame that transforms into an illuminated photo display when switched on.",
    requiredPhotos: "1 High-Quality Photo",
    requiredDetails: "",
    photoSize: "",
  },

  /* ---------------- FRAMES ---------------- */
  {
    slug: "frames-customized-photo-frame",
    name: "Customized Photo Frame",
    category: "frames",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/frames/frames-1.jpg",
    description: "High quality wooden framed photo print.",
    requiredPhotos: "1 High-Quality Photo",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "single-photo-frame",
    name: "Single Photo Frame",
    category: "frames",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/frames/frames-2.jpg",
    description: "Classic single photo table or wall frame.",
    requiredPhotos: "1 High-Quality Photo",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "frames-couple-photo-frame",
    name: "Couple Photo Frame",
    category: "frames",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/frames/frames-3.jpg",
    description: "Romantic photo frame styled for couples.",
    requiredPhotos: "1–2 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "family-photo-frame",
    name: "Family Photo Frame",
    category: "frames",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/frames/frames-4.jpg",
    description: "Large wall frame customized with your family portrait.",
    requiredPhotos: "1–5 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "kids-photo-frame",
    name: "Kids Photo Frame",
    category: "frames",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/frames/frames-5.jpg",
    description: "Playful designs for capturing childhood memories.",
    requiredPhotos: "1 High-Quality Photo",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "friendship-photo-frame",
    name: "Friendship Photo Frame",
    category: "frames",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/frames/frames-6.jpg",
    description: "Friendship themed custom photo frame.",
    requiredPhotos: "1–4 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "birthday-photo-frame",
    name: "Birthday Photo Frame",
    category: "frames",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/frames/frames-7.jpg",
    description: "Decorative frame with birthday themed prints.",
    requiredPhotos: "1–3 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "frames-anniversary-photo-frame",
    name: "Anniversary Photo Frame",
    category: "frames",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/frames/frames-8.jpg",
    description: "Premium anniversary photo frame.",
    requiredPhotos: "1–2 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "frames-collage-photo-frame",
    name: "Collage Photo Frame",
    category: "frames",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/frames/frames-9.jpg",
    description: "Multi-photo grid collage frame.",
    requiredPhotos: "6–12 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "frames-mosaic-photo-frame",
    name: "Mosaic Photo Frame",
    category: "frames",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/frames/frames-10.jpg",
    description: "High-density photo mosaic frame.",
    requiredPhotos: "30–60 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },

  /* ---------------- KEYCHAINS ---------------- */
  {
    slug: "customized-keychain",
    name: "Customized Keychain",
    category: "keychains",
    price: "₹79",
    oldPrice: "₹158",
    offer: "50% OFF",
    image: "/images/keychains/keychain-1.jpg",
    description: "Durable personalized acrylic or metal keychain.",
    requiredPhotos: "1 High-Quality Photo",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "name-keychain",
    name: "Name Keychain",
    category: "keychains",
    price: "₹79",
    oldPrice: "₹158",
    offer: "50% OFF",
    image: "/images/keychains/keychain-2.jpg",
    description: "Custom cut acrylic name keychain.",
    requiredPhotos: "None",
    requiredDetails: "Custom Name",
    photoSize: "",
  },
  {
    slug: "photo-keychain",
    name: "Photo Keychain",
    category: "keychains",
    price: "₹79",
    oldPrice: "₹158",
    offer: "50% OFF",
    image: "/images/keychains/keychain-3.jpg",
    description: "Double sided photo keychain.",
    requiredPhotos: "1–2 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "couple-keychain",
    name: "Couple Keychain",
    category: "keychains",
    price: "₹79",
    oldPrice: "₹158",
    offer: "50% OFF",
    image: "/images/keychains/keychain-4.jpg",
    description: "Interlocking or matching pair keychains for couples.",
    requiredPhotos: "1–2 High-Quality Photos",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "logo-keychain",
    name: "Logo Keychain",
    category: "keychains",
    price: "₹79",
    oldPrice: "₹158",
    offer: "50% OFF",
    image: "/images/keychains/keychain-5.jpg",
    description: "Custom keychains printed with personal or corporate logos.",
    requiredPhotos: "1 Logo File",
    requiredDetails: "",
    photoSize: "",
  },

  /* ---------------- CUSTOMIZED T SHIRT ---------------- */
  {
    slug: "personalized-tshirt",
    name: "Personalized T Shirt",
    category: "customized-t-shirt",
    price: "₹249",
    oldPrice: "₹498",
    offer: "50% OFF",
    image: "/images/tshirts/tshirts-1.jpg",
    description: "100% Cotton custom printed t-shirt with your photos or graphics.",
    requiredPhotos: "1 High-Quality Image",
    requiredDetails: "T-Shirt Size (S, M, L, XL, XXL)",
    photoSize: "",
  },
  {
    slug: "name-printed-tshirt",
    name: "Name Printed T Shirt",
    category: "customized-t-shirt",
    price: "₹249",
    oldPrice: "₹498",
    offer: "50% OFF",
    image: "/images/tshirts/tshirts-2.jpg",
    description: "Custom t-shirt printed with personalized typography or name text.",
    requiredPhotos: "Optional Image",
    requiredDetails: "Name / Text & T-Shirt Size",
    photoSize: "",
  },
  {
    slug: "couple-tshirt",
    name: "Couple T Shirt",
    category: "customized-t-shirt",
    price: "₹249",
    oldPrice: "₹498",
    offer: "50% OFF",
    image: "/images/tshirts/tshirts-3.jpg",
    description: "Matching set of t-shirts designed for couples.",
    requiredPhotos: "Optional Image",
    requiredDetails: "Sizes for both T-Shirts",
    photoSize: "",
  },
  {
    slug: "birthday-tshirt",
    name: "Birthday T Shirt",
    category: "customized-t-shirt",
    price: "₹249",
    oldPrice: "₹498",
    offer: "50% OFF",
    image: "/images/tshirts/tshirts-4.jpg",
    description: "Custom birthday squad or birthday boy/girl t-shirt.",
    requiredPhotos: "1 High-Quality Photo",
    requiredDetails: "Age/Name & T-Shirt Size",
    photoSize: "",
  },
  {
    slug: "family-tshirt",
    name: "Family T Shirt",
    category: "customized-t-shirt",
    price: "₹249",
    oldPrice: "₹498",
    offer: "50% OFF",
    image: "/images/tshirts/tshirts-5.jpg",
    description: "Matching family theme custom printed t-shirt set.",
    requiredPhotos: "Optional Image",
    requiredDetails: "Family Roles & Sizes",
    photoSize: "",
  },
  {
    slug: "friendship-tshirt",
    name: "Friendship T Shirt",
    category: "customized-t-shirt",
    price: "₹249",
    oldPrice: "₹498",
    offer: "50% OFF",
    image: "/images/tshirts/tshirts-6.jpg",
    description: "Fun matching graphics t-shirts for friend groups.",
    requiredPhotos: "Optional Image",
    requiredDetails: "Custom Text & T-Shirt Sizes",
    photoSize: "",
  },

  /* ---------------- ACRYLIC FRAMES ---------------- */
  {
    slug: "customized-acrylic-frame",
    name: "Customized Acrylic Frame",
    category: "acrylic-frames",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/placeholder.jpg",
    description: "Sleek glass-like acrylic photo frame with vibrant direct UV printing.",
    requiredPhotos: "1 High-Quality Photo",
    requiredDetails: "",
    photoSize: "",
  },
  {
    slug: "birthday-acrylic-frame",
    name: "Birthday Acrylic Frame",
    category: "acrylic-frames",
    price: "₹349",
    oldPrice: "₹698",
    offer: "50% OFF",
    image: "/images/placeholder.jpg",
    description: "Vibrant birthday themed acrylic frame display.",
    requiredPhotos: "1–3 High-Quality Photos",
    requiredDetails: "Name / Birth Date",
    photoSize: "",
  },

  /* ---------------- STICKERS & LABELS ---------------- */
 {
  slug: "custom-sticker",
  name: "Customized Sticker",
  category: "stickers-and-labels",
  price: "₹25",
  oldPrice: "₹50",
  offer: "50% OFF",
  image: "/images/stickers/stickers-1.jpg",
  description: "Custom stickers per sheet for personal and business use.",
  requiredPhotos: "Optional",
  requiredDetails: "Custom Design",
  photoSize: "",
},
{
  slug: "customized-sticker-chocolates",
  name: "Customized Sticker Chocolates",
  category: "stickers-and-labels",
  price: "₹20",
  oldPrice: "₹40",
  offer: "50% OFF",
  image: "/images/stickers/stickers-2.jpg",
  description: "Custom printed wrapper chocolates per piece.",
  requiredPhotos: "Optional",
  requiredDetails: "Custom Text / Photo",
  photoSize: "",
},
{
  slug: "customized-notebook-name-label",
  name: "Customized Notebook Name Label",
  category: "stickers-and-labels",
  price: "₹25",
  oldPrice: "₹50",
  offer: "50% OFF",
  image: "/images/stickers/stickers-3.jpg",
  description: "Personalized notebook labels per sheet.",
  requiredPhotos: "Optional",
  requiredDetails: "Student Name / Subject Info",
  photoSize: "",
},
{
  slug: "business-branding-labels",
  name: "Business and Branding Labels",
  category: "stickers-and-labels",
  price: "₹25",
  oldPrice: "₹50",
  offer: "50% OFF",
  image: "/images/stickers/stickers-4.jpg",
  description: "High quality branding labels per sheet.",
  requiredPhotos: "1 Logo File",
  requiredDetails: "",
  photoSize: "",
},
{
  slug: "gift-stickers",
  name: "Gift Stickers",
  category: "stickers-and-labels",
  price: "₹25",
  oldPrice: "₹50",
  offer: "50% OFF",
  image: "/images/stickers/stickers-5.jpg",
  description: "Decorative custom gift stickers per sheet.",
  requiredPhotos: "Optional",
  requiredDetails: "",
  photoSize: "",
},
{
  slug: "event-stickers",
  name: "Event Stickers",
  category: "stickers-and-labels",
  price: "₹25",
  oldPrice: "₹50",
  offer: "50% OFF",
  image: "/images/stickers/stickers-1-2.jpg",
  description: "Custom event labels and stickers per sheet.",
  requiredPhotos: "Optional",
  requiredDetails: "",
  photoSize: "",
},
{
  slug: "home-personal-label",
  name: "Home and Personal Label",
  category: "stickers-and-labels",
  price: "₹25",
  oldPrice: "₹50",
  offer: "50% OFF",
  image: "/images/stickers/stickers-4-2.jpg",
  description: "Personalized labeling per sheet for home items.",
  requiredPhotos: "Optional",
  requiredDetails: "",
  photoSize: "",
},
{
  slug: "packaging-labels",
  name: "Packaging Labels",
  category: "stickers-and-labels",
  price: "₹25",
  oldPrice: "₹50",
  offer: "50% OFF",
  image: "/images/stickers/stickers-5-2.jpg",
  description: "Custom packaging labels per sheet.",
  requiredPhotos: "1 Logo File",
  requiredDetails: "",
  photoSize: "",
},
];