export const categories = [
  { name: "Birthday", slug: "birthday", icon: "🎂" },
  { name: "Anniversary", slug: "anniversary", icon: "💝" },
  { name: "Couple", slug: "couple", icon: "👩‍❤️‍👨" },
  { name: "Corporate", slug: "corporate", icon: "💼" },
  { name: "Combo", slug: "combo", icon: "🎁" },
  { name: "Mugs", slug: "mugs", icon: "☕" },
  { name: "Frames", slug: "frames", icon: "🖼️" },
  { name: "Keychains", slug: "keychains", icon: "🔑" },
  { name: "Customized T Shirt", slug: "customized-t-shirt", icon: "👕" },
  { name: "Acrylic Frames", slug: "acrylic-frames", icon: "✨" },
  { name: "Stickers and Labels", slug: "stickers-and-labels", icon: "🏷️" },
  { name: "Resin Art", slug: "resin-art", icon: "🌊" },
];

export const products = [

  {
    slug: "customized-photo-collage",
    name: "Customized Photo Collage",
    category: "featured",
    price: "₹499",
    oldPrice: "₹899",
    offer: "45% OFF",
    image: "/images/best1.jpg",
  },

  {
    slug: "google-collage-frame",
    name: "Google Collage Frame",
    category: "featured",
    price: "₹599",
    oldPrice: "₹999",
    offer: "40% OFF",
    image: "/images/best2.jpg",
  },

  {
    slug: "spotify-photo-frame",
    name: "Spotify Photo Frame",
    category: "featured",
    price: "₹399",
    oldPrice: "₹699",
    offer: "42% OFF",
    image: "/images/best3.jpg",
  },

  {
    slug: "moon-shape-photo-frame",
    name: "Moon Shape Photo Frame",
    category: "featured",
    price: "₹799",
    oldPrice: "₹1299",
    offer: "38% OFF",
    image: "/images/best4.jpg",
  },

  {
    slug: "photo-clip-string-light",
    name: "Photo Clip String Light",
    category: "featured",
    price: "₹349",
    oldPrice: "₹699",
    offer: "50% OFF",
    image: "/images/new1.jpg",
  },

  {
    slug: "customized-photo-prints",
    name: "Customized Photo Prints",
    category: "featured",
    price: "₹299",
    oldPrice: "₹599",
    offer: "50% OFF",
    image: "/images/new2.jpg",
  },

  {
    slug: "custom-photo-collage",
    name: "Custom Photo Collage",
    category: "featured",
    price: "₹449",
    oldPrice: "₹899",
    offer: "50% OFF",
    image: "/images/new3.jpg",
  },

  {
    slug: "students-teacher-photo-frame",
    name: "Students & Teacher Photo Frame",
    category: "featured",
    price: "₹599",
    oldPrice: "₹999",
    offer: "40% OFF",
    image: "/images/new4.jpg",
  },
  // BIRTHDAY
  {
    slug: "birthday-customized-photo-frame",
    name: "Customized Photo Frame",
    category: "birthday",
    price: "₹499",
    oldPrice: "₹899",
    offer: "45% OFF",
    image: "/images/birthday/birthday-sample-1.jpg",
  },
  {
    slug: "birthday-collage-photo-frame",
    name: "Collage Photo Frame",
    category: "birthday",
    price: "₹599",
    oldPrice: "₹999",
    offer: "40% OFF",
    image: "/images/birthday/birthday-sample-2.jpg",
  },
  {
    slug: "birthday-photo-clock",
    name: "Photo Clock",
    category: "birthday",
    price: "₹350",
    oldPrice: "₹699",
    offer: "50% OFF",
    image: "/images/birthday/birthday-sample-4.jpg",
  },
  {
    slug: "birthday-photo-calendar",
    name: "Photo Calendar",
    category: "birthday",
    price: "₹250",
    oldPrice: "₹499",
    offer: "50% OFF",
    image: "/images/birthday/birthday-sample-5.jpg",
  },
  {
    slug: "birthday-customized-mugs",
    name: "Birthday Customized Mugs",
    category: "birthday",
    price: "₹299",
    oldPrice: "₹499",
    offer: "40% OFF",
    image: "/images/birthday/birthday-sample-6.jpg",
  },
  {
    slug: "birthday-custom-keychains",
    name: "Birthday Custom Keychains",
    category: "birthday",
    price: "₹180",
    oldPrice: "₹399",
    offer: "55% OFF",
    image: "/images/birthday/birthday-sample-7.jpg",
  },
  {
    slug: "birthday-magazines",
    name: "Birthday Magazines",
    category: "birthday",
    price: "₹650",
    oldPrice: "₹999",
    offer: "35% OFF",
    image: "/images/birthday/birthday-sample-8.jpg",
  },
  {
    slug: "birthday-custom-photo-book",
    name: "Custom Photo Book",
    category: "birthday",
    price: "₹999",
    oldPrice: "₹1599",
    offer: "38% OFF",
    image: "/images/birthday/birthday-sample-9.jpg",
  },

// ANNIVERSARY
{
  slug: "anniversary-photo-frame",
  name: "Anniversary Photo Frame",
  category: "anniversary",
  price: "₹499",
  oldPrice: "₹899",
  offer: "45% OFF",
  image: "/images/anniversary/anniversary-1.jpg",
},
{
  slug: "anniversary-collage-photo-frame",
  name: "Collage Photo Frame",
  category: "anniversary",
  price: "₹599",
  oldPrice: "₹999",
  offer: "40% OFF",
  image: "/images/anniversary/anniversary-2.jpg",
},
{
  slug: "anniversary-mosaic-photo-frame",
  name: "Mosaic Photo Frame",
  category: "anniversary",
  price: "₹699",
  oldPrice: "₹1199",
  offer: "42% OFF",
  image: "/images/anniversary/anniversary-3.jpg",
},
{
  slug: "anniversary-acrylic-photo-frame",
  name: "Acrylic Photo Frame",
  category: "anniversary",
  price: "₹799",
  oldPrice: "₹1299",
  offer: "38% OFF",
  image: "/images/anniversary/anniversary-4.jpg",
},
{
  slug: "anniversary-photo-wall-collage",
  name: "Photo Wall Collage",
  category: "anniversary",
  price: "₹899",
  oldPrice: "₹1499",
  offer: "40% OFF",
  image: "/images/anniversary/anniversary-5.jpg",
},
{
  slug: "anniversary-mugs",
  name: "Anniversary Mugs",
  category: "anniversary",
  price: "₹350",
  oldPrice: "₹599",
  offer: "42% OFF",
  image: "/images/anniversary/anniversary-6.jpg",
},
{
  slug: "anniversary-keychains",
  name: "Anniversary Keychains",
  category: "anniversary",
  price: "₹180",
  oldPrice: "₹399",
  offer: "55% OFF",
  image: "/images/anniversary/anniversary-7.jpg",
},
{
  slug: "anniversary-custom-photo-book",
  name: "Custom Photo Book",
  category: "anniversary",
  price: "₹999",
  oldPrice: "₹1599",
  offer: "38% OFF",
  image: "/images/anniversary/anniversary-8.jpg",
},
{
  slug: "love-message-frame",
  name: "Love Message Frame",
  category: "anniversary",
  price: "₹499",
  oldPrice: "₹899",
  offer: "45% OFF",
  image: "/images/anniversary/anniversary-9.jpg",
},

  // COUPLE
  {
    slug: "couple-photo-frame",
    name: "Couple Photo Frame",
    category: "couple",
    price: "₹499",
    oldPrice: "₹899",
    offer: "45% OFF",
    image: "/images/couple/couple-1.jpg",
  },
  {
    slug: "customized-couple-mugs",
    name: "Customized Couple Mugs",
    category: "couple",
    price: "₹350",
    oldPrice: "₹599",
    offer: "42% OFF",
    image: "/images/couple/couple-2.jpg",
  },
  {
    slug: "couple-customized-keychains",
    name: "Customized Keychains",
    category: "couple",
    price: "₹180",
    oldPrice: "₹399",
    offer: "55% OFF",
    image: "/images/couple/couple-3.jpg",
  },
  {
    slug: "love-message-photo-frame",
    name: "Love Message Photo Frame",
    category: "couple",
    price: "₹599",
    oldPrice: "₹999",
    offer: "40% OFF",
    image: "/images/couple/couple-4.jpg",
  },
  {
    slug: "couple-acrylic-photo-frame",
    name: "Acrylic Photo Frame",
    category: "couple",
    price: "₹799",
    oldPrice: "₹1299",
    offer: "38% OFF",
    image: "/images/couple/couple-5.jpg",
  },
  {
    slug: "couple-collage-photo-frame",
    name: "Collage Photo Frame",
    category: "couple",
    price: "₹699",
    oldPrice: "₹1199",
    offer: "42% OFF",
    image: "/images/couple/couple-6.jpg",
  },
  {
    slug: "couple-mosaic-photo-frame",
    name: "Mosaic Photo Frame",
    category: "couple",
    price: "₹899",
    oldPrice: "₹1499",
    offer: "40% OFF",
    image: "/images/couple/couple-7.jpg",
  },
  {
    slug: "customized-photo-album",
    name: "Customized Photo Album",
    category: "couple",
    price: "₹999",
    oldPrice: "₹1599",
    offer: "38% OFF",
    image: "/images/couple/couple-8.jpg",
  },
  {
    slug: "couple-customized-photo-book",
    name: "Customized Photo Book",
    category: "couple",
    price: "₹1199",
    oldPrice: "₹1999",
    offer: "40% OFF",
    image: "/images/couple/couple-9.jpg",
  },
  {
    slug: "customized-magazines",
    name: "Customized Magazines",
    category: "couple",
    price: "₹650",
    oldPrice: "₹999",
    offer: "35% OFF",
    image: "/images/couple/couple-10.jpg",
  },

  // CORPORATE
  {
    slug: "corporate-customized-mug",
    name: "Customized Mug",
    category: "corporate",
    price: "₹350",
    oldPrice: "₹599",
    offer: "42% OFF",
    image: "/images/corporate/corporate-1.jpg",
  },
  {
    slug: "corporate-customized-keychains",
    name: "Customized Keychains",
    category: "corporate",
    price: "₹180",
    oldPrice: "₹399",
    offer: "55% OFF",
    image: "/images/corporate/corporate-2.jpg",
  },
  {
    slug: "customized-water-bottle",
    name: "Customized Water Bottle",
    category: "corporate",
    price: "₹499",
    oldPrice: "₹899",
    offer: "45% OFF",
    image: "/images/corporate/corporate-3.jpg",
  },
  {
    slug: "corporate-photo-frame",
    name: "Photo Frame",
    category: "corporate",
    price: "₹599",
    oldPrice: "₹999",
    offer: "40% OFF",
    image: "/images/corporate/corporate-4.jpg",
  },
  {
    slug: "logo-printed-keychains",
    name: "Logo Printed Keychains",
    category: "corporate",
    price: "₹250",
    oldPrice: "₹499",
    offer: "50% OFF",
    image: "/images/corporate/corporate-5.jpg",
  },
  {
    slug: "customized-calendar",
    name: "Customized Calendar",
    category: "corporate",
    price: "₹399",
    oldPrice: "₹699",
    offer: "43% OFF",
    image: "/images/corporate/corporate-6.jpg",
  },
  {
    slug: "motivational-photo-frame",
    name: "Motivational Photo Frame",
    category: "corporate",
    price: "₹699",
    oldPrice: "₹1199",
    offer: "42% OFF",
    image: "/images/corporate/corporate-8.jpg",
  },
  {
    slug: "wall-frames",
    name: "Wall Frames",
    category: "corporate",
    price: "₹999",
    oldPrice: "₹1599",
    offer: "38% OFF",
    image: "/images/corporate/corporate-9.jpg",
  },

  // COMBO
  {
    slug: "photo-frame-mug-combo",
    name: "Photo Frame + Mug",
    category: "combo",
    price: "₹699",
    oldPrice: "₹1199",
    offer: "42% OFF",
    image: "/images/combo/combo-1.jpg",
  },
  {
    slug: "mug-keychains-combo",
    name: "Mug + Keychains",
    category: "combo",
    price: "₹499",
    oldPrice: "₹899",
    offer: "45% OFF",
    image: "/images/combo/combo-2.jpg",
  },
  {
    slug: "photo-frame-keychains-combo",
    name: "Photo Frame + Keychains",
    category: "combo",
    price: "₹599",
    oldPrice: "₹999",
    offer: "40% OFF",
    image: "/images/combo/combo-3.jpg",
  },
  {
    slug: "mug-greeting-card-combo",
    name: "Mug + Greeting Card",
    category: "combo",
    price: "₹350",
    oldPrice: "₹599",
    offer: "42% OFF",
    image: "/images/combo/combo-4.jpg",
  },

  // MUGS
  {
    slug: "photo-mug",
    name: "Photo Mug",
    category: "mugs",
    price: "₹250",
    oldPrice: "₹499",
    offer: "50% OFF",
    image: "/images/mugs/mugs-1.jpg",
  },
  {
    slug: "couple-mug-item",
    name: "Couple Mug",
    category: "mugs",
    price: "₹299",
    oldPrice: "₹499",
    offer: "40% OFF",
    image: "/images/mugs/mugs-2.jpg",
  },
  {
    slug: "magic-mug",
    name: "Magic Mug",
    category: "mugs",
    price: "₹350",
    oldPrice: "₹599",
    offer: "42% OFF",
    image: "/images/mugs/mugs-3.jpg",
  },
  {
    slug: "name-printed-mugs",
    name: "Name Printed Mugs",
    category: "mugs",
    price: "₹250",
    oldPrice: "₹499",
    offer: "50% OFF",
    image: "/images/mugs/mugs-4.jpg",
  },
  {
    slug: "birthday-mug",
    name: "Birthday Mug",
    category: "mugs",
    price: "₹299",
    oldPrice: "₹499",
    offer: "40% OFF",
    image: "/images/mugs/mugs-5.jpg",
  },
  {
    slug: "best-friends-mug",
    name: "Best Friends Mug",
    category: "mugs",
    price: "₹299",
    oldPrice: "₹499",
    offer: "40% OFF",
    image: "/images/mugs/mugs-6.jpg",
  },
  {
    slug: "anniversary-mug",
    name: "Anniversary Mug",
    category: "mugs",
    price: "₹350",
    oldPrice: "₹599",
    offer: "42% OFF",
    image: "/images/mugs/mugs-7.jpg",
  },
  {
    slug: "magic-mirror",
    name: "Magic Mirror",
    category: "mugs",
    price: "₹799",
    oldPrice: "₹1299",
    offer: "38% OFF",
    image: "/images/mugs/mugs-8.jpg",
  },

  // FRAMES
  {
    slug: "frames-customized-photo-frame",
    name: "Customized Photo Frame",
    category: "frames",
    price: "₹499",
    oldPrice: "₹899",
    offer: "45% OFF",
    image: "/images/frames/frames-1.jpg",
  },
  {
    slug: "single-photo-frame",
    name: "Single Photo Frame",
    category: "frames",
    price: "₹350",
    oldPrice: "₹599",
    offer: "42% OFF",
    image: "/images/frames/frames-2.jpg",
  },
  {
    slug: "frames-couple-photo-frame",
    name: "Couple Photo Frame",
    category: "frames",
    price: "₹599",
    oldPrice: "₹999",
    offer: "40% OFF",
    image: "/images/frames/frames-3.jpg",
  },
  {
    slug: "family-photo-frame",
    name: "Family Photo Frame",
    category: "frames",
    price: "₹699",
    oldPrice: "₹1199",
    offer: "42% OFF",
    image: "/images/frames/frames-4.jpg",
  },
  {
    slug: "kids-photo-frame",
    name: "Kids Photo Frame",
    category: "frames",
    price: "₹499",
    oldPrice: "₹899",
    offer: "45% OFF",
    image: "/images/frames/frames-5.jpg",
  },
  {
    slug: "friendship-photo-frame",
    name: "Friendship Photo Frame",
    category: "frames",
    price: "₹599",
    oldPrice: "₹999",
    offer: "40% OFF",
    image: "/images/frames/frames-6.jpg",
  },
  {
    slug: "birthday-photo-frame",
    name: "Birthday Photo Frame",
    category: "frames",
    price: "₹699",
    oldPrice: "₹1199",
    offer: "42% OFF",
    image: "/images/frames/frames-7.jpg",
  },
  {
    slug: "frames-anniversary-photo-frame",
    name: "Anniversary Photo Frame",
    category: "frames",
    price: "₹799",
    oldPrice: "₹1299",
    offer: "38% OFF",
    image: "/images/frames/frames-8.jpg",
  },
  {
    slug: "frames-collage-photo-frame",
    name: "Collage Photo Frame",
    category: "frames",
    price: "₹899",
    oldPrice: "₹1499",
    offer: "40% OFF",
    image: "/images/frames/frames-9.jpg",
  },
  {
    slug: "frames-mosaic-photo-frame",
    name: "Mosaic Photo Frame",
    category: "frames",
    price: "₹999",
    oldPrice: "₹1599",
    offer: "38% OFF",
    image: "/images/frames/frames-10.jpg",
  },
  {
    slug: "frames-acrylic-photo-frame",
    name: "Acrylic Photo Frame",
    category: "frames",
    price: "₹999",
    oldPrice: "₹1699",
    offer: "41% OFF",
    image: "/images/frames/frames-11.jpg",
  },

  // KEYCHAINS
  {
    slug: "customized-keychain",
    name: "Customized Keychain",
    category: "keychains",
    price: "₹180",
    oldPrice: "₹399",
    offer: "55% OFF",
    image: "/images/keychains/keychain-1.jpg",
  },
  {
    slug: "name-keychain",
    name: "Name Keychain",
    category: "keychains",
    price: "₹180",
    oldPrice: "₹399",
    offer: "55% OFF",
    image: "/images/keychains/keychain-2.jpg",
  },
  {
    slug: "photo-keychain",
    name: "Photo Keychain",
    category: "keychains",
    price: "₹250",
    oldPrice: "₹499",
    offer: "50% OFF",
    image: "/images/keychains/keychain-3.jpg",
  },
  {
    slug: "couple-keychain",
    name: "Couple Keychain",
    category: "keychains",
    price: "₹299",
    oldPrice: "₹499",
    offer: "40% OFF",
    image: "/images/keychains/keychain-4.jpg",
  },
  {
    slug: "logo-keychain",
    name: "Logo Keychain",
    category: "keychains",
    price: "₹350",
    oldPrice: "₹599",
    offer: "42% OFF",
    image: "/images/keychains/keychain-5.jpg",
  },

  // CUSTOMIZED T SHIRT
  {
    slug: "personalized-tshirt",
    name: "Personalized T Shirt",
    category: "customized-t-shirt",
    price: "₹499",
    oldPrice: "₹899",
    offer: "45% OFF",
    image: "/images/tshirts/tshirts-1.jpg",
  },
  {
    slug: "name-printed-tshirt",
    name: "Name Printed T Shirt",
    category: "customized-t-shirt",
    price: "₹499",
    oldPrice: "₹899",
    offer: "45% OFF",
    image: "/images/tshirts/tshirts-2.jpg",
  },
  {
    slug: "couple-tshirt",
    name: "Couple T Shirt",
    category: "customized-t-shirt",
    price: "₹799",
    oldPrice: "₹1299",
    offer: "38% OFF",
    image: "/images/tshirts/tshirts-3.jpg",
  },
  {
    slug: "birthday-tshirt",
    name: "Birthday T Shirt",
    category: "customized-t-shirt",
    price: "₹599",
    oldPrice: "₹999",
    offer: "40% OFF",
    image: "/images/tshirts/tshirts-4.jpg",
  },
  {
    slug: "family-tshirt",
    name: "Family T Shirt",
    category: "customized-t-shirt",
    price: "₹999",
    oldPrice: "₹1599",
    offer: "38% OFF",
    image: "/images/tshirts/tshirts-5.jpg",
  },
  {
    slug: "friendship-tshirt",
    name: "Friendship T Shirt",
    category: "customized-t-shirt",
    price: "₹699",
    oldPrice: "₹1199",
    offer: "42% OFF",
    image: "/images/tshirts/tshirts-6.jpg",
  },

  // ACRYLIC FRAMES
  {
    slug: "customized-acrylic-frame",
    name: "Customized Acrylic Frame",
    category: "acrylic-frames",
    price: "₹799",
    oldPrice: "₹1299",
    offer: "38% OFF",
    image: "/images/placeholder.jpg",
  },
  {
    slug: "birthday-acrylic-frame",
    name: "Birthday Acrylic Frame",
    category: "acrylic-frames",
    price: "₹799",
    oldPrice: "₹1299",
    offer: "38% OFF",
    image: "/images/placeholder.jpg",
  },
  {
    slug: "anniversary-acrylic-frame",
    name: "Anniversary Acrylic Frame",
    category: "acrylic-frames",
    price: "₹899",
    oldPrice: "₹1499",
    offer: "40% OFF",
    image: "/images/placeholder.jpg",
  },
  {
    slug: "couple-acrylic-frame",
    name: "Couple Acrylic Frame",
    category: "acrylic-frames",
    price: "₹899",
    oldPrice: "₹1499",
    offer: "40% OFF",
    image: "/images/placeholder.jpg",
  },
  {
    slug: "family-acrylic-frame",
    name: "Family Acrylic Frame",
    category: "acrylic-frames",
    price: "₹999",
    oldPrice: "₹1599",
    offer: "38% OFF",
    image: "/images/placeholder.jpg",
  },
  {
    slug: "friends-acrylic-frame",
    name: "Friends Acrylic Frame",
    category: "acrylic-frames",
    price: "₹799",
    oldPrice: "₹1299",
    offer: "38% OFF",
    image: "/images/placeholder.jpg",
  },

  // STICKERS AND LABELS
  {
    slug: "customized-sticker",
    name: "Customized Sticker",
    category: "stickers-and-labels",
    price: "₹180",
    oldPrice: "₹399",
    offer: "55% OFF",
    image: "/images/stickers/stickers-1.jpg",
  },
  {
    slug: "customized-sticker-chocolates",
    name: "Customized Sticker Chocolates",
    category: "stickers-and-labels",
    price: "₹250",
    oldPrice: "₹499",
    offer: "50% OFF",
    image: "/images/stickers/stickers-2.jpg",
  },
  {
    slug: "customized-notebook-name-label",
    name: "Customized Notebook Name Label",
    category: "stickers-and-labels",
    price: "₹150",
    oldPrice: "₹299",
    offer: "50% OFF",
    image: "/images/stickers/stickers-3.jpg",
  },
  {
    slug: "business-branding-labels",
    name: "Business and Branding Labels",
    category: "stickers-and-labels",
    price: "₹350",
    oldPrice: "₹599",
    offer: "42% OFF",
    image: "/images/stickers/stickers-4.jpg",
  },
  {
    slug: "gift-stickers",
    name: "Gift Stickers",
    category: "stickers-and-labels",
    price: "₹199",
    oldPrice: "₹399",
    offer: "50% OFF",
    image: "/images/stickers/stickers-5.jpg",
  },
  {
    slug: "event-stickers",
    name: "Event Stickers",
    category: "stickers-and-labels",
    price: "₹299",
    oldPrice: "₹499",
    offer: "40% OFF",
    image: "/images/stickers/stickers-6.jpg",
  },
  {
    slug: "home-personal-label",
    name: "Home and Personal Label",
    category: "stickers-and-labels",
    price: "₹250",
    oldPrice: "₹499",
    offer: "50% OFF",
    image: "/images/stickers/stickers-7.jpg",
  },
  {
    slug: "packaging-labels",
    name: "Packaging Labels",
    category: "stickers-and-labels",
    price: "₹399",
    oldPrice: "₹699",
    offer: "43% OFF",
    image: "/images/stickers/stickers-8.jpg",
  },

  // RESIN ART
  {
    slug: "customized-resin-art",
    name: "Customized Resin Art",
    category: "resin-art",
    price: "₹999",
    oldPrice: "₹1599",
    offer: "38% OFF",
    image: "/images/placeholder.jpg",
  },
];